// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlUpyTuvDbP-y830A1FWRvn9ZB_GEmDQA',
    appId: '1:200843617348:web:1070d5a79380f9c9384811',
    messagingSenderId: '200843617348',
    projectId: 'chatapptute-b3d5d',
    authDomain: 'chatapptute-b3d5d.firebaseapp.com',
    storageBucket: 'chatapptute-b3d5d.firebasestorage.app',
    measurementId: 'G-2FVSXWF56S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATvW699O_S3E_439_F58ucxkKwZaQK-5g',
    appId: '1:200843617348:android:477a4b6b06d56036384811',
    messagingSenderId: '200843617348',
    projectId: 'chatapptute-b3d5d',
    storageBucket: 'chatapptute-b3d5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL5XoPYIihtzoYqnZEi9s12yKy1HwVUkk',
    appId: '1:200843617348:ios:f7f2cfca8d7ac2b2384811',
    messagingSenderId: '200843617348',
    projectId: 'chatapptute-b3d5d',
    storageBucket: 'chatapptute-b3d5d.firebasestorage.app',
    iosBundleId: 'com.example.flutterMiniChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL5XoPYIihtzoYqnZEi9s12yKy1HwVUkk',
    appId: '1:200843617348:ios:f7f2cfca8d7ac2b2384811',
    messagingSenderId: '200843617348',
    projectId: 'chatapptute-b3d5d',
    storageBucket: 'chatapptute-b3d5d.firebasestorage.app',
    iosBundleId: 'com.example.flutterMiniChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlUpyTuvDbP-y830A1FWRvn9ZB_GEmDQA',
    appId: '1:200843617348:web:644f7734398272c8384811',
    messagingSenderId: '200843617348',
    projectId: 'chatapptute-b3d5d',
    authDomain: 'chatapptute-b3d5d.firebaseapp.com',
    storageBucket: 'chatapptute-b3d5d.firebasestorage.app',
    measurementId: 'G-PZ2VCEWDBZ',
  );
}
